const briefingItems = [
  {
    n: "01",
    title: "Approve MEP variation (+1.2M AED)",
    body: "Consultant review complete. Waiting on your signature for 2 days.",
    chips: ["VAR-018", "cites 4 sources", "value 1.2M AED"],
    cta: { label: "Review decision →", primary: true },
  },
  {
    n: "02",
    title: "Escalate RFI-124 to consultant",
    body: "Blocking concrete pour on Tower B. Open 11 days.",
    chips: ["RFI-124", "cites 7 sources", "crit-path · 2d"],
    cta: { label: "Open RFI →", primary: false },
  },
  {
    n: "03",
    title: "Review risk: rebar delivery delay",
    body: "Pulse projects +3 day critical path impact if unmitigated.",
    chips: ["RISK-007", "cites 5 sources", "mitigation drafted"],
    cta: { label: "View risk →", primary: false },
  },
];

const projectFacts = [
  { label: "Role", value: "Owner / Developer" },
  { label: "Counterparts", value: "Arup · Mace · 4 more" },
  { label: "Tools connected", value: "ACC · Procore · P6" },
  { label: "Contract", value: "FIDIC Red 1999 + bespoke" },
];

const cadence = [
  { label: "Daily morning brief", desc: "06:00 · weekdays", on: false },
  { label: "Weekly briefing", desc: "Mon 06:00", on: true },
  { label: "Real-time alerts", desc: "critical only", on: true },
  { label: "Mobile push (field)", desc: "blockers + RFIs", on: false },
];

const startupStats = [
  { value: "3,482", label: "documents indexed", sub: "across ACC, Procore, P6" },
  { value: "142", label: "RFIs reconciled", sub: "9 over 30 days" },
  { value: "38", label: "decisions extracted", sub: "from emails + minutes" },
  { value: "12", label: "risks surfaced", sub: "3 critical-path" },
];

export function SkeletonFirstBriefingStep() {
  return (
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1fr_320px]">
      <div className="space-y-6">
        <p className="text-sm text-neutral-600">
          Pulse spent the last few minutes reading 3,482 documents and 28 months
          of schedule. Here&apos;s what it thinks deserves your attention first
          — every claim links back to its source.
        </p>

        <section className="rounded-md border border-neutral-300 bg-white">
          <header className="flex items-center justify-between border-b border-neutral-200 px-5 py-4">
            <div>
              <p className="text-[10px] uppercase tracking-widest text-neutral-500">
                Monday briefing · 14 Nov 2026 · generated by Pulse
              </p>
              <h2 className="mt-2 text-xl font-semibold">
                3 things need your attention this week.
              </h2>
              <p className="mt-1 text-xs text-neutral-500">
                Drawn from this week&apos;s RFI activity, schedule slip vs
                baseline, and contract obligations coming due.
              </p>
            </div>
            <span className="text-[10px] text-neutral-500">
              5-min read · audio version 4:12
            </span>
          </header>
          <ul className="divide-y divide-neutral-200">
            {briefingItems.map((item) => (
              <li
                key={item.n}
                className="flex items-start gap-4 px-5 py-4"
              >
                <span className="font-mono text-xs text-neutral-500">
                  {item.n}
                </span>
                <div className="flex-1">
                  <p className="text-sm font-semibold">{item.title}</p>
                  <p className="mt-1 text-xs text-neutral-600">{item.body}</p>
                  <div className="mt-2 flex flex-wrap gap-2 text-[10px] text-neutral-500">
                    {item.chips.map((c) => (
                      <span
                        key={c}
                        className="rounded border border-neutral-200 bg-neutral-50 px-1.5 py-0.5 font-mono"
                      >
                        {c}
                      </span>
                    ))}
                  </div>
                </div>
                <span
                  className={
                    item.cta.primary
                      ? "rounded-md border border-neutral-900 bg-neutral-900 px-3 py-1.5 text-xs text-white"
                      : "rounded-md border border-neutral-900 bg-white px-3 py-1.5 text-xs text-neutral-900"
                  }
                >
                  {item.cta.label}
                </span>
              </li>
            ))}
          </ul>
          <div className="flex items-center justify-between border-t border-neutral-200 px-5 py-3 text-xs text-neutral-500">
            <span>
              Briefings arrive Monday 06:00 — adjust in{" "}
              <span className="underline">Settings → Cadence</span>
            </span>
            <span className="flex items-center gap-2">
              <span className="rounded-full border border-neutral-300 px-3 py-1">
                ↓ Export
              </span>
              <span className="rounded-full border border-neutral-300 px-3 py-1">
                + Adjust priorities
              </span>
            </span>
          </div>
        </section>

        <section className="rounded-md border border-neutral-300 bg-white">
          <header className="flex items-center justify-between border-b border-neutral-200 px-5 py-4">
            <p className="text-[10px] uppercase tracking-widest text-neutral-500">
              Since you started setup, Pulse has
            </p>
            <span className="text-[10px] text-neutral-500">
              4 min 12 sec elapsed
            </span>
          </header>
          <ul className="grid grid-cols-2 gap-3 p-5 md:grid-cols-4">
            {startupStats.map((s) => (
              <li
                key={s.value}
                className="rounded-md border border-neutral-200 bg-neutral-50 p-4"
              >
                <p className="text-2xl font-semibold">{s.value}</p>
                <p className="mt-1 text-xs text-neutral-700">{s.label}</p>
                <p className="text-[10px] text-neutral-500">{s.sub}</p>
              </li>
            ))}
          </ul>
        </section>
      </div>

      <aside className="space-y-4">
        <div className="rounded-md border border-neutral-300 bg-white p-4">
          <p className="text-[10px] uppercase tracking-widest text-neutral-500">
            Your project
          </p>
          <p className="mt-2 text-base font-semibold">Marina Tower Phase 2</p>
          <p className="text-xs text-neutral-500">
            847M AED · 28 months · started Jan 2026
          </p>
          <ul className="mt-3 divide-y divide-neutral-200 border-t border-neutral-200 pt-2 text-xs">
            {projectFacts.map((f) => (
              <li
                key={f.label}
                className="flex items-baseline justify-between py-2"
              >
                <span className="uppercase tracking-widest text-[10px] text-neutral-500">
                  {f.label}
                </span>
                <span className="text-neutral-700">{f.value}</span>
              </li>
            ))}
          </ul>
          <p className="mt-3 text-[10px] text-neutral-500">
            <span className="underline">Edit setup</span> · anytime, no
            re-onboarding
          </p>
        </div>

        <div className="rounded-md border border-neutral-300 bg-white p-4">
          <p className="text-[10px] uppercase tracking-widest text-neutral-500">
            Choose your cadence
          </p>
          <ul className="mt-3 space-y-3">
            {cadence.map((c) => (
              <li
                key={c.label}
                className="flex items-start justify-between gap-3"
              >
                <div>
                  <p className="text-xs font-semibold">{c.label}</p>
                  <p className="text-[10px] text-neutral-500">{c.desc}</p>
                </div>
                <span
                  className={
                    c.on
                      ? "flex h-4 w-7 items-center justify-end rounded-full bg-neutral-900 px-0.5"
                      : "flex h-4 w-7 items-center justify-start rounded-full bg-neutral-200 px-0.5"
                  }
                  aria-label={c.on ? "On" : "Off"}
                >
                  <span className="h-3 w-3 rounded-full bg-white" />
                </span>
              </li>
            ))}
          </ul>
        </div>

        <div className="rounded-md border border-dashed border-neutral-300 bg-white p-4">
          <p className="text-[10px] uppercase tracking-widest text-neutral-500">
            Need a hand?
          </p>
          <p className="mt-2 text-xs text-neutral-700">
            A Pulse architect will walk your team through the dashboard in the
            first week — no charge.
          </p>
          <span className="mt-3 inline-block rounded-full border border-neutral-300 bg-white px-3 py-1 text-xs text-neutral-700">
            Book a 30-min walkthrough →
          </span>
        </div>
      </aside>
    </div>
  );
}
